# spring configuration
spring:
   application:
      name: service-emaillist
   profiles:
      active: development

            
---
# configuration: common
spring:
   cloud:
      config:
         enabled: true
         uri: http://localhost:7777
         

---
# configuration: development > localhost여도 돌아가는 이유는 config-repo에 설정
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777                 
      
---
# configuration: production > linux 서버 배포용이면 ip, aws면 ec2 ip
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.92:7777

      
